### ISSUE TITLE
Turn on/off rebalancing purchases

### ISSUE THREAD

**Issue by salixlabs** [j4c0b1-fromspace-com-br/3ca#1]
**Is your feature request related to a problem? Please describe.**
The returns in my brokerage account are much less than what the 3C bots say I should have, and this is largely due to portfolio rebalancing when the grid resets itself. I'd like an option to turn that on or off. The problem with this is that the bot then places large market orders (much larger than the quantity you trade with each grid) and given how grid bot works, these orders always sell low and buy high. 

**Describe the solution you'd like**
If I have funds available to move the grid to a new upper & lower limit, then reset the grid with those new limits. If I don't have the funds to do so, then don't market buy and don't move the limits and just leave the grid where it's at.

**Describe alternatives you've considered**
Running fewer grids and making the grid quantity much larger to cover all of the USD and coin I have, or just managing the grids manually myself. The problem with that solution is I would have to trade much less capital compared to using infinity grid bot.

**Additional context**
My CBP exchange account is up about $1k net of fees over the last week, even though 3C shows that I should be up $9k (around $7k after fees) so this is having a drastic impact on performance.

**Comment by cj4c0b1** [comment]
Hi @sky-sail 
Sorry by the late update.
This feature was implemented already.
You can activate this option using a custom arg -nr
It will not do the re balancing, will still continue to update the range, but because of 3commas api limitations there is no way to automatically start your bot. so you should manage when you want to apply the re-balance and start your bots.
This feature as you describe was implemented on another project "advanced grids" but this one do not use 3commas,
if you have any doubts on how to use the new args just ask in the telegram group or dm me.
